FROM python:3.6
RUN git clone https://github.com/frickler24/RechteDB.git

WORKDIR /RechteDB
RUN pip install -r RechteDB/requirements/prod.txt
COPY .env .env

WORKDIR /RechteDB/RechteDB
RUN ./manage.py collectstatic

CMD "gunicorn" "-c" "guniconf.py" "RechteDB.wsgi"

